package com.alexzh.designsystem.core.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF2E7D32)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFC8E6C9)
val onPrimaryContainerLight = Color(0xFF00220A)
val secondaryLight = Color(0xFF2E7D32)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC8E6C9)
val onSecondaryContainerLight = Color(0xFF00220A)
val tertiaryLight = Color(0xFF2E7D32)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC8E6C9)
val onTertiaryContainerLight = Color(0xFF00220A)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFE9EAEE)
val onBackgroundLight = Color(0xFF191C1D)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF191C1D)
val surfaceVariantLight = Color(0xFFE1E2EC)
val onSurfaceVariantLight = Color(0xFF44474F)
val outlineLight = Color(0xFF75777F)
val outlineVariantLight = Color(0xFFC5C7D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F312D)
val inverseOnSurfaceLight = Color(0xFFF0F1EB)
val inversePrimaryLight = Color(0xFF2E7D32)
val surfaceDimLight = Color(0xFFD8DAE0)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFFFFF)
val surfaceContainerLight = Color(0xFFEFF0F4)
val surfaceContainerHighLight = Color(0xFFE4E5E9)
val surfaceContainerHighestLight = Color(0xFFDEE0E4)

val primaryDark = Color(0xFF81C784)
val onPrimaryDark = Color(0xFF003913)
val primaryContainerDark = Color(0xFF0A531B)
val onPrimaryContainerDark = Color(0xFF9CF6A0)
val secondaryDark = Color(0xFF81C784)
val onSecondaryDark = Color(0xFF003913)
val secondaryContainerDark = Color(0xFF0A531B)
val onSecondaryContainerDark = Color(0xFF9CF6A0)
val tertiaryDark = Color(0xFF81C784)
val onTertiaryDark = Color(0xFF003913)
val tertiaryContainerDark = Color(0xFF0A531B)
val onTertiaryContainerDark = Color(0xFF9CF6A0)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF121411)
val onBackgroundDark = Color(0xFFE2E3DD)
val surfaceDark = Color(0xFF1A1C19)
val onSurfaceDark = Color(0xFFE2E3DD)
val surfaceVariantDark = Color(0xFF424940)
val onSurfaceVariantDark = Color(0xFFC2C9BD)
val outlineDark = Color(0xFF8C9388)
val outlineVariantDark = Color(0xFF424940)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E3DD)
val inverseOnSurfaceDark = Color(0xFF2F312D)
val inversePrimaryDark = Color(0xFF2E7D32)
val surfaceDimDark = Color(0xFF121411)
val surfaceBrightDark = Color(0xFF383A36)
val surfaceContainerLowestDark = Color(0xFF1A1C19)
val surfaceContainerLowDark = Color(0xFF222421)
val surfaceContainerDark = Color(0xFF262825)
val surfaceContainerHighDark = Color(0xFF313330)
val surfaceContainerHighestDark = Color(0xFF3C3E3A)

/**
 * Chart colors (70% opacity)
 */
val chartColorZeroLight = surfaceVariantLight.copy(alpha = 0.6f)
val chartColorZeroDark = surfaceVariantDark.copy(alpha = 0.6f)
val chartColorLowValuesLight = Color(0xB3E55A6D)
val chartColorLowValuesDark = Color(0xB3e55a6d)
val chartColorMediumValuesLight = Color(0xB3CBB2D0)
val chartColorMediumValuesDark = Color(0xB3CBB2D0)
val chartColorHighValuesLight = Color(0xB39FD48A)
val chartColorHighValuesDark = Color(0xB39FD48A)